id = "neovim-default"
name = "Neovim default themes"
version = "0.1.0"
schema_version = 1
authors = ["Kim Nørgaard"]
description = "A port of the default Neovim themes"
repository = "https://github.com/KimNorgaard/zed-neovim-default.git"
